//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanAppPOC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomTableLayout
    {
        public int CustomTableLayoutId { get; set; }
        public string JsonLayoutInstructions { get; set; }
        public string AspNetUsersId { get; set; }
        public string GridName { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
